version: "3"

services:
  nginx:
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: "${USER}.42.fr"
    container_name: nginx
    volumes:
      - wp-pages:/var/www/wordpress
      - adminer-volume:/var/www/adminer
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://${USER}.42.fr"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception
    init: true

  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        WP_DATABASE_NAME: ${WP_DATABASE_NAME}
        WP_DATABASE_USER: ${WP_DATABASE_USER}
        WP_DATABASE_PASSWORD: ${WP_DATABASE_PASSWORD}
        WP_DATABASE_ROOT: ${WP_DATABASE_ROOT}
        WP_DATABASE_ROOT_PASSWORD: ${WP_DATABASE_ROOT_PASSWORD}
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file: .env
    networks:
      - inception
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  inception:
    driver: bridge
    name: inception

volumes:
  wp-pages:
  adminer-volume:
  wordpress:
  mariadb-data:
