version: "3"

services:
  nginx:
    build:
      context: ./requirements/nginx
      args:
        UID: "${UID}"
        DOMAIN_NAME: "${LOGIN}.42.fr"
    container_name: nginx
    volumes:
      - wp-pages:/var/www/wordpress
      - adminer-volume:/var/www/adminer
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    user:
      "${UID}:${GID}"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://${LOGIN}.42.fr"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wp-pages:/var/www/wordpress
    env_file: .env
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception
    init: true

  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        WP_DATABASE_NAME: ${WP_DATABASE_NAME}
        WP_DATABASE_USER: ${WP_DATABASE_USER}
        WP_DATABASE_PASSWORD: ${WP_DATABASE_PASSWORD}
        WP_DATABASE_ROOT: ${WP_DATABASE_ROOT}
        WP_DATABASE_ROOT_PASSWORD: ${WP_DATABASE_ROOT_PASSWORD}
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - wp-database:/var/lib/mysql
    env_file: .env
    networks:
      - inception
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "${HEALTH_USER}", "-p${HEALTH_PASS}", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    build:
      context: ./bonus/adminer
    container_name: adminer
    volumes:
      - adminer-volume:/var/www/adminer
    networks:
      - inception
    restart:
      always
    depends_on:
      - mariadb

  redis:
    image: redis
    build:
      context: ./bonus/redis
    container_name: redis
    networks:
      - inception
    restart:
      always
    depends_on:
      - wordpress

  site:
    image: site
    build:
      context: ./bonus/site
    container_name: site
    networks:
      - inception
    restart:
      always

networks:
  inception:
    driver: bridge
    name: inception

volumes:
  wp-pages:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${DATA_DIR}/wp-pages'
  wp-database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${DATA_DIR}/wp-database'
  adminer-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${DATA_DIR}/adminer-volume'
