#!/bin/bash

mariadb-install-db --user=mysql --datadir=/var/lib/mysql

mariadbd-safe --datadir=/var/lib/mysql &
sleep 5

echo "DB_NAME=$WP_DATABASE_NAME"
echo "DB_USER=$WP_DATABASE_USER"
echo "DB_PASSWORD=$WP_DATABASE_PASSWORD"

mariadb -u root <<EOF
DROP USER IF EXISTS '${WP_DATABASE_USER}'@'%';
DROP USER IF EXISTS '${WP_DATABASE_ROOT}'@'localhost';
DROP USER IF EXISTS ''@'localhost';
DROP DATABASE IF EXISTS test;
CREATE DATABASE IF NOT EXISTS \`${WP_DATABASE_NAME}\`;
CREATE USER '${WP_DATABASE_USER}'@'%' IDENTIFIED BY '${WP_DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${WP_DATABASE_NAME}\`.* TO '${WP_DATABASE_USER}'@'%';
CREATE USER '${WP_DATABASE_ROOT}'@'localhost' IDENTIFIED BY '${WP_DATABASE_ROOT_PASSWORD}';
ALTER USER '${WP_DATABASE_ROOT}'@'localhost' IDENTIFIED BY '${WP_DATABASE_ROOT_PASSWORD}';
FLUSH PRIVILEGES;
EOF

mariadb-admin -u root -p${WP_DATABASE_ROOT_PASSWORD} shutdown
