DROP USER IF EXISTS ''@'localhost';

DROP DATABASE IF EXISTS test;

CREATE DATABASE IF NOT EXISTS `${WP_DATABASE_NAME}`;

CREATE USER IF NOT EXISTS '${WP_DATABASE_USER}'@'%' IDENTIFIED BY '${WP_DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON `${WP_DATABASE_NAME}`.* TO '${WP_DATABASE_USER}'@'%';

ALTER USER 'root'@'localhost' IDENTIFIED BY '${WP_DATABASE_ROOT_PASSWORD}';

CREATE USER IF NOT EXISTS '${HEALTH_USER}'@'localhost' IDENTIFIED BY '${HEALTH_PASS}';
GRANT USAGE ON *.* TO '${HEALTH_USER}'@'localhost';

FLUSH PRIVILEGES;